import datetime
import os
from pathlib import Path

BASE = Path(__file__).resolve().parents[1]
INDEX = BASE / "index.html"
POSTS = BASE / "posts"
POSTS.mkdir(exist_ok=True)

TOPICS = [
    ("示例文章 1", "Example Article 1", "example-1"),
    ("示例文章 2", "Example Article 2", "example-2"),
    ("示例文章 3", "Example Article 3", "example-3"),
]

def generate_post():
    now = datetime.datetime.utcnow()
    zh_title, en_title, slug = TOPICS[now.minute % len(TOPICS)]
    year = now.strftime('%Y')

    zh_content = f"""
<h1>{zh_title}</h1>
<p>发布时间：{now.strftime('%Y-%m-%d %H:%M UTC')}</p>
<p>本文由 GitHub Actions 自动生成。</p>
"""

    en_content = f"""
<h1>{en_title}</h1>
<p>Published at: {now.strftime('%Y-%m-%d %H:%M UTC')}</p>
<p>This article is automatically generated by GitHub Actions.</p>
"""

    html = f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <title>{zh_title} | {en_title}</title>
  <meta name="description" content="{zh_title} / {en_title} 自动发布内容">
</head>
<body>
<section lang="zh">{zh_content}</section>
<hr>
<section lang="en">{en_content}</section>
<a href="../../index.html">Back to Home</a>
</body>
</html>"""

    post_dir = POSTS / year
    post_dir.mkdir(exist_ok=True)
    path = post_dir / f"{slug}.html"
    path.write_text(html, encoding="utf-8")

    return zh_title, en_title, f"posts/{year}/{slug}.html", now


def update_index(post):
    zh_title, en_title, link, now = post
    marker = "<!-- POSTS -->"
    if INDEX.exists():
        html = INDEX.read_text(encoding="utf-8")
        entry = f"<article><h2><a href=\"{link}\">{zh_title} / {en_title}</a></h2><time>{now.strftime('%Y-%m-%d')}</time></article>\n{marker}"
        INDEX.write_text(html.replace(marker, entry), encoding="utf-8")

if __name__ == '__main__':
    post = generate_post()
    update_index(post)
